SELECT * FROM DATA_APPLICATION_FOR_MANAGER
SELECT * FROM DATA_APPLICATION_FOR_EMPLOYEE
SELECT * FROM DATA_APPLICATION_REGISTER
SELECT * FROM DATA_APPLICATION_USER
SELECT ncc.ID,mcc.UserName FROM DATA_APPLICATION_REGISTER mcc,DATA_APPLICATION_USER ncc WHERE ncc.UserName=mcc.UserName
SELECT ncc.ID,mcc.UserName FROM DATA_APPLICATION_REGISTER mcc,DATA_APPLICATION_USER ncc WHERE ncc.UserName=mcc.UserName

DELETE DATA_APPLICATION_USER WHERE UserName='rongchoi9'

SELECT ncc.ID,mcc.UserName FROM DATA_APPLICATION_REGISTER mcc,DATA_APPLICATION_USER ncc WHERE ncc.UserName=mcc.UserName
SELECT * FROM DATA_APPLICATION_REGISTER

INSERT INTO DATA_APPLICATION_FOR_EMPLOYEE VALUES ('{Username}',



SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER(ID,UserName,UserPassword,TAI_KHOANG)
SELECT '{ID}','{Username}','{Userpassword}','TAI_KHOANG'
SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER OFF

SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER(ID,UserName,UserPassword,TAI_KHOANG)
SELECT '6','Nv04',PWDENCRYPT('Nv04@123'),'EMPLOYEE'
SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER OFF


SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON
INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,FristName,LastName,EmailAdress,SDT_MANAGER,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'QL02','NGUYEN THANH VINH', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'NGUYEN','VINH','vinh2002@gmail.com',MANAGER.SDT_MANAGER,DATA_APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM dbo.DATA_APPLICATION_FOR_MANAGER,DATA_APPLICATION_REGISTER,DATA_APPLICATION_USER
WHERE DATA_APPLICATION_USER.ID=3 AND MANAGER.TENQL='NGUYEN THANH VINH'
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER OFF 



SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON INSERT INTO dbo.DATA_APPLICATION_USER(ID,UserName,UserPassword,TAI_KHOANG) SELECT '{ID}','{Username}','{Userpassword}','TAI_KHOANG' SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER OFF


SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON
INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,FristName,LastName,EmailAdress,SDT_MANAGER,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'{Usercode}','{Nameuser}', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'{Fristname}','{Lastname}','{EmailAdress}','{SDT_MANAGER}','{TAI_KHOANG}','12/21/2022'
FROM dbo.DATA_APPLICATION_FOR_MANAGER,DATA_APPLICATION_USER
WHERE DATA_APPLICATION_USER.UserName='{Username}';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER OFF 


SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE ON
INSERT INTO dbo.DATA_APPLICATION_FOR_EMPLOYEE (ID,MaNV,TenNV,UserName,UserPassword,FristName,LastName,EmailAdress,SDT_EMPLOYEE,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'NV04','NGUYEN TRUNG KHANH', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'NGUYEN','KHANH','NGUYENTRUNG@gmail.com','09467626532',DATA_APPLICATION_USER.TAI_KHOANG,'12/29/2022'
FROM DATA_APPLICATION_USER
WHERE DATA_APPLICATION_USER.ID=6 and DATA_APPLICATION_USER.UserName='Nv04';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYE OFF 

DELETE dbo.DATA_APPLICATION_FOR_EMPLOYEE WHERE MaNV='NV04'


SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE ON INSERT INTO dbo.DATA_APPLICATION_FOR_EMPLOYEE (ID,MaNV,TenNV,UserName,UserPassword,FristName,LastName,EmailAdress,SDT_EMPLOYEE,TAI_KHOANG,NGAY_DANG_KY) SELECT DATA_APPLICATION_USER.ID,'Nv07','Nguyen vo khanh', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'Nguyen','Khanh','khanhyou2020@gmail.com','012345678',DATA_APPLICATION_USER.TAI_KHOANG,'12/30/2022' FROM DATA_APPLICATION_USER WHERE DATA_APPLICATION_USER.ID=9 and DATA_APPLICATION_USER.UserName='rongchoi9'
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,FristName,LastName,EmailAdress,SDT_MANAGER,TAI_KHOANG,NGAY_DANG_KY) SELECT DATA_APPLICATION_USER.ID,'{Usercode}','{Nameuser}', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'{Fristname}','{Lastname}','{EmailAdress}','{SDT_USER}',DATA_APPLICATION_USER.TAI_KHOANG,'{NGAY_DANG_KY}' FROM DATA_APPLICATION_USER WHERE DATA_APPLICATION_USER.ID={ID} and DATA_APPLICATION_USER.UserName='{Username}'; SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYE OFF 