CREATE DATABASE QLKH
GO

CREATE TABLE NHACUNGCAP(
	MACC CHAR(10) NOT NULL,
	TENCC NVARCHAR(50),
	SANPHAM NVARCHAR(50),
	SL INT,
	GIA MONEY,
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50),

	constraint PK_NCC primary key(MACC)
)

CREATE TABLE MANAGER(
	MAQL CHAR(10) NOT NULL,
	TENQL NVARCHAR(50),
	LUONG MONEY,
	THUONG FLOAT,
	GIOITINH CHAR(10),
	NGAYSINH DATE,
	SOTHICH NVARCHAR,
	DIACHI NVARCHAR,

	constraint PK_MANAGER primary key(MAQL)
) 

CREATE TABLE KHOHANG(
	MAKHO CHAR(10) NOT NULL,
	TENKHO NVARCHAR(50),
	TONGSL INT,
	BAONHIEULOAI INT,

	constraint PK_KHOHANG primary key(MAKHO,TENKHO)
)

CREATE TABLE MATHANG(
	MAMATHANG CHAR(10) NOT NULL,
	TENMATHANG NVARCHAR(50),
	LOAI NVARCHAR(30),
	SL INT,
	GIA MONEY,

	constraint PK_MATHANG primary key(MAMATHANG,TENMATHANG)
)

CREATE TABLE NHANVIEN(
	MANV CHAR(10) NOT NULL,
	TENNV NVARCHAR(50),
	LUONG MONEY,
	THUONG FLOAT,
	GIOITINH CHAR(10),
	NGAYSINH DATE,
	SOTHICH NVARCHAR,
	DIACHI NVARCHAR,
	
	constraint PK_NHANVIEN primary key(MANV)
)

CREATE TABLE KHACHHANG(
	MAKH CHAR(10) NOT NULL,
	TENKH NVARCHAR(50),
	SDT VARCHAR(10),
	DIACHI NVARCHAR(50),

	constraint PK_MAKH primary key(MAKH)
)


CREATE TABLE MANAGER_NHACUNGCAP_KHOHANG(
	SOHD_NHAPHANGVE CHAR(10) NOT NULL,
	TENHD NVARCHAR(50),
	SL INT,
	TONGGIA MONEY,

	constraint PK_MANAGER_NHACUNGCAP_KHOHANG PRIMARY KEY(SOHD_NHAPHANGVE,TENHD)
)

CREATE TABLE MANAGER_KHO(
	SOHD_NHAPHANG_KHO CHAR(10) NOT NULL,
	TENHD NVARCHAR(50),
	SL INT,
	SL_CACLOAI INT,
	TONGIA MONEY,

	constraint PK_MANAGER_KHO primary key(SOHD_NHAPHANG_KHO,TENHD)

)

CREATE TABLE KHO_MATHANG(
	SO_CTHD CHAR(10) NOT NULL,
	TEN_CTHD NVARCHAR(50),
	TINHTRANG NVARCHAR(20),
	LOAI NVARCHAR(20),
	GIA MONEY,
	SL INT,

	constraint PK_KHO_MATHANG primary key(SO_CTHD,TEN_CTHD)
)


