USE PLANTCARE6
GO

CREATE TABLE dbo.classADMIN(
MaAD char(15),
TenAD nvarchar(100),

constraint PK_CLASSADMIN primary key(MaAD,TenAD)
)

GO

CREATE TABLE dbo.DATA_APPLICATION_REGISTER(
UserName nvarchar(100) not null,
UserPassword nvarchar(100) not null,
FristName nvarchar(30),
LastName nvarchar(30),
EmailAdress nvarchar(50),
Date_of_birth date,
NGAY_DANG_KY date,

constraint PK_DATA_APPLICATION_REGISTER PRIMARY KEY(UserName,UserPassword,EmailAdress)
)

GO

CREATE TABLE dbo.ACTIVEDATA_LOGIN(
ACTIVE_ID int identity,
UserName nvarchar(100),
UserPassword nvarchar(100),
NGAY_DANG_NHAP date,

constraint PK_ACTIVEDATA_LOGIN PRIMARY KEY(ACTIVE_ID)
)
GO

CREATE TABLE dbo.DATA_APPLICATION_USER(
 ID int identity NOT NULL,
 UserName nvarchar(100) NOT NULL,
 UserPassword nvarchar(100) NOT NULL,
 TAI_KHOANG nvarchar(30),
 constraint PK_DATA_APPLICATION_USER primary key(ID)
)

GO

CREATE TABLE dbo.DATA_APPLICATION_FOR_ADMIN(
ID int identity,
MaAD char(15),
TenAD nvarchar(100),
UserName nvarchar(100),
UserPassword nvarchar(100),
FristName nvarchar(30),
LastName nvarchar(30),
EmailAdress nvarchar(50),
TAI_KHOANG nvarchar(30),
NGAY_DANG_KY DATE,

)
GO

CREATE TABLE dbo.DATA_APPLICATION_FOR_MANAGER(
ID int identity,
MaQL char(15),
TenQL nvarchar(100),
UserName nvarchar(100),
UserPassword nvarchar(100),
FristName nvarchar(30),
LastName nvarchar(30),
EmailAdress nvarchar(50),
SDT_MANAGER varchar(15),
TAI_KHOANG nvarchar(30),
NGAY_DANG_KY DATE,

)
GO

CREATE TABLE dbo.DATA_APPLICATION_FOR_EMPLOYEE(
ID int identity,
MaNV char(15),
TenNV nvarchar(100),
UserName nvarchar(100),
UserPassword nvarchar(100),
FristName nvarchar(30),
LastName nvarchar(30),
EmailAdress nvarchar(50),
SDT_EMPLOYEE nvarchar(15),
TAI_KHOANG nvarchar(30),
NGAY_DANG_KY DATE,

)
GO

--Insert into classADMIN
INSERT INTO dbo.CLASSADMIN VALUES ('AD01','ADMIN01')


--Insert into Application for Admin
Insert Into dbo.DATA_APPLICATION_REGISTER
SELECT 'Admin',PWDENCRYPT('Admin@123'),'NGUYEN','KHANH','khanhyou2018@gmail.com',(SELECT NGAYSINH FROM MANAGER WHERE TENQL='NGUYEN VO KHANH'),'12/25/2022'

--Isernt into Application forManager
Insert Into dbo.DATA_APPLICATION_REGISTER
SELECT 'khanh1803',PWDENCRYPT('Khanh1803@2002'),'NGUYEN','KHANH','khanhyou2018@gmail.com',(SELECT NGAYSINH FROM MANAGER WHERE TENQL='NGUYEN VO KHANH'),'12/25/2022'

Insert Into dbo.DATA_APPLICATION_REGISTER
SELECT 'vinh123',PWDENCRYPT('Vinh123@2002'),'NGUYEN','VINH','vinh2002@gmail.com',(SELECT NGAYSINH FROM MANAGER WHERE TENQL='NGUYEN THANH VINH'),'12/25/2022'

--Insert into Application for Employee
Insert Into dbo.DATA_APPLICATION_REGISTER
SELECT 'Nv02',PWDENCRYPT('Nv02@123'),'TRAN','LOC','nv02@gmail.com','03/18/2002','12/25/2022'

Insert Into dbo.DATA_APPLICATION_REGISTER
SELECT 'Nv03',PWDENCRYPT('Nv03@123'),'LE','KHAI','nv03@gmail.com','03/18/2002','12/25/2022'


SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER (ID,UserName,UserPassword,TAI_KHOANG)
SELECT 1,DATA_APPLICATION_REGISTER.UserName,DATA_APPLICATION_REGISTER.UserPassword,'ADMIN'
FROM DATA_APPLICATION_REGISTER
WHERE DATA_APPLICATION_REGISTER.UserName='Admin';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF

SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER (ID,UserName,UserPassword,TAI_KHOANG)
SELECT 2,DATA_APPLICATION_REGISTER.UserName,DATA_APPLICATION_REGISTER.UserPassword,'MANAGER'
FROM DATA_APPLICATION_REGISTER
WHERE DATA_APPLICATION_REGISTER.UserName='khanh1803';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF

SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER (ID,UserName,UserPassword,TAI_KHOANG)
SELECT 3,DATA_APPLICATION_REGISTER.UserName,DATA_APPLICATION_REGISTER.UserPassword,'MANAGER'
FROM DATA_APPLICATION_REGISTER
WHERE DATA_APPLICATION_REGISTER.UserName='vinh123';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF

SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER (ID,UserName,UserPassword,TAI_KHOANG)
SELECT 4,DATA_APPLICATION_REGISTER.UserName,DATA_APPLICATION_REGISTER.UserPassword,'EMPLOYEE'
FROM DATA_APPLICATION_REGISTER
WHERE DATA_APPLICATION_REGISTER.UserName='Nv02';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF

SET IDENTITY_INSERT dbo.DATA_APPLICATION_USER ON
INSERT INTO dbo.DATA_APPLICATION_USER (ID,UserName,UserPassword,TAI_KHOANG)
SELECT 5,DATA_APPLICATION_REGISTER.UserName,DATA_APPLICATION_REGISTER.UserPassword,'EMPLOYEE'
FROM DATA_APPLICATION_REGISTER
WHERE DATA_APPLICATION_REGISTER.UserName='Nv03';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF


--Insert into Data for DATA_APPLICATION_FOR_ADMIN

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN ON
INSERT INTO dbo.DATA_APPLICATION_FOR_ADMIN (ID,MaAD,TenAD,UserName,UserPassword,FristName,LastName,EmailAdress,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'AD01','ADMIN01', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'Nguyen','Khanh','khanhyou2018@gmail.com',DATA_APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM DATA_APPLICATION_USER 
WHERE DATA_APPLICATION_USER.UserName='Admin';
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF 


--INSERT INTO DATA FOR DATA_APPLICATION FOR_MANAGER
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON
INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,FristName,LastName,EmailAdress,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'QL01','NGUYEN VO KHANH', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'NGUYEN','KHANH','khanhyou2018@gmail.com',DATA_APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM DATA_APPLICATION_USER 
WHERE DATA_APPLICATION_USER.ID=2;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER OFF 

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON
INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,FristName,LastName,EmailAdress,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'QL02','NGUYEN THANH VINH', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'NGUYEN','VINH','vinh2002@gmail.com',DATA_APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM DATA_APPLICATION_USER 
WHERE DATA_APPLICATION_USER.ID=3;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER OFF 



SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE ON
INSERT INTO dbo.DATA_APPLICATION_FOR_EMPLOYEE (ID,MaNV,TenNV,UserName,UserPassword,FristName,LastName,EmailAdress,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'NV02','TRAN VO LOC', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'TRAN','LOC','locnv01@gmail.com',DATA_APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM DATA_APPLICATION_USER 
WHERE DATA_APPLICATION_USER.ID=4;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE OFF 

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE ON
INSERT INTO dbo.DATA_APPLICATION_FOR_EMPLOYEE (ID,MaNV,TenNV,UserName,UserPassword,EmailAdress,FristName,LastName,TAI_KHOANG,NGAY_DANG_KY)
SELECT DATA_APPLICATION_USER.ID,'NV03','LE PHU KHAI', DATA_APPLICATION_USER.UserName, DATA_APPLICATION_USER.UserPassword,'LE','KHAI','khainv02@gmail.com',DATA_APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM DATA_APPLICATION_USER 
WHERE DATA_APPLICATION_USER.ID=5;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE OFF 

--INSERT DATA_APPLICATION_REGISTER

--ALTAER TABLE REFERENCRS DATA_APPLICATION_REGISTER
ALTER TABLE dbo.DATA_APPLICATION_FOR_ADMIN ADD CONSTRAINT FK_DATA_APPLICATION_FOR_ADMIN FOREIGN KEY (UserName,UserPassword,EmailAdress) REFERENCES dbo.DATA_APPLICATION_REGISTER(UserName,UserPassword,EmailAdress)
ALTER TABLE dbo.DATA_APPLICATION_FOR_MANAGER ADD CONSTRAINT FK_DATA_APPLICATION_FOR_MANAGER FOREIGN KEY (UserName,UserPassword,EmailAdress) REFERENCES dbo.DATA_APPLICATION_REGISTER(UserName,UserPassword,EmailAdress)
ALTER TABLE dbo.DATA_APPLICATION_FOR_EMPLOYEE ADD CONSTRAINT FK_DATA_APPLICATION_FOR_EMPLOYEE FOREIGN KEY (UserName,UserPassword,EmailAdress) REFERENCES dbo.DATA_APPLICATION_REGISTER(UserName,UserPassword,EmailAdress)

ALTER TABLE dbo.DATA_APPLICATION_FOR_ADMIN ADD CONSTRAINT FK_DATA_APPLICATION_FOR_ADMIN FOREIGN KEY (MaAD) REFERENCES dbo.classADMIN(MaAD)
ALTER TABLE dbo.DATA_APPLICATION_FOR_MANAGER ADD CONSTRAINT FK_DATA_APPLICATION_FOR_MANAGER FOREIGN KEY (MaQL,SDT_MANAGER) REFERENCES dbo.MANAGER(MaQL,SDT_MANAGER)
ALTER TABLE dbo.DATA_APPLICATION_FOR_EMPLOYEE ADD CONSTRAINT FK_DATA_APPLICATION_FOR_EMPLOYEE FOREIGN KEY (MaQL,SDT_EMPLOYEE) REFERENCES dbo.NHANVIEN(MaQL,SDT_EMPLOYEE)


ALTER TABLE dbo.DATA_APPLICATION_USER ADD CONSTRAINT FK_DATA_APPLICATION_USER FOREIGN KEY(UserName,UserPassword) REFERENCES dbo.DATA_APPLICATION_REGISTER(UserName,UserPassword)

