USE PLANTCARE6
GO

CREATE TABLE dbo.CLASSADMIN(
MaAD char(15),
TenAD nvarchar(100),

constraint PK_CLASSADMIN primary key(MaAD,TenAD)
)

GO

CREATE TABLE dbo.APPLICATION_USER(
 ID int identity NOT NULL,
 UserName nvarchar(100) NOT NULL,
 UserPassword nvarchar(100) NOT NULL,
 TAI_KHOANG nvarchar(30),
 constraint PK_APPLICATION_USER primary key(ID,Username,UserPassword)
)

GO

CREATE TABLE dbo.DATA_APPLICATION_FOR_ADMIN(
ID int identity,
MaAD char(15),
TenAD nvarchar(100),
UserName nvarchar(100),
UserPassword nvarchar(100),
TAI_KHOANG nvarchar(30),
NGAY_DANG_NHAP DATE,

)
GO

CREATE TABLE dbo.DATA_APPLICATION_FOR_MANAGER(
ID int identity,
MaQL char(15),
TenQL nvarchar(100),
UserName nvarchar(100),
UserPassword nvarchar(100),
TAI_KHOANG nvarchar(30),
NGAY_DANG_NHAP DATE,

)
GO

CREATE TABLE dbo.DATA_APPLICATION_FOR_EMPLOYEE(
ID int identity,
MaNV char(15),
TenNV nvarchar(100),
UserName nvarchar(100),
UserPassword nvarchar(100),
TAI_KHOANG nvarchar(30),
NGAY_DANG_NHAP DATE,

)
GO

--Insert into Application for Admin
Insert Into dbo.APPLICATION_USER
SELECT 'Admin',PWDENCRYPT('Admin@123'),'ADMIN'

--Isernt into Application forManager
Insert Into APPLICATION_USER
SELECT 'khanh1803',PWDENCRYPT('Khanh1803@2002'),'MANAGER'

Insert Into APPLICATION_USER
SELECT 'vinh123',PWDENCRYPT('Vinh123@2002'),'MANAGER'

--Insert into Application for Employee
Insert Into APPLICATION_USER
SELECT 'Nv02',PWDENCRYPT('Nv02@123'),'EMPLOYEE'

Insert Into APPLICATION_USER
SELECT 'Nv03',PWDENCRYPT('Nv03@123'),'EMPLOYEE'

--Insert into Data for DATA_APPLICATION_FOR_ADMIN

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN ON
INSERT INTO dbo.DATA_APPLICATION_FOR_ADMIN (ID,MaAD,TenAD,UserName,UserPassword,TAI_KHOANG,NGAY_DANG_NHAP)
SELECT APPLICATION_USER.ID,'AD01','ADMIN01', APPLICATION_USER.UserName, APPLICATION_USER.UserPassword,APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM APPLICATION_USER 
WHERE APPLICATION_USER.ID=1;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_ADMIN OFF 


--INSERT INTO DATA FOR DATA_APPLICATION FOR_MANAGER
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON
INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,TAI_KHOANG,NGAY_DANG_NHAP)
SELECT APPLICATION_USER.ID,'QL01','NGUYEN VO KHANH', APPLICATION_USER.UserName, APPLICATION_USER.UserPassword,APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM APPLICATION_USER 
WHERE APPLICATION_USER.ID=2;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER OFF 

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER ON
INSERT INTO dbo.DATA_APPLICATION_FOR_MANAGER (ID,MaQL,TenQL,UserName,UserPassword,TAI_KHOANG,NGAY_DANG_NHAP)
SELECT APPLICATION_USER.ID,'QL02','NGUYEN THANH VINH', APPLICATION_USER.UserName, APPLICATION_USER.UserPassword,APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM APPLICATION_USER 
WHERE APPLICATION_USER.ID=3;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_MANAGER OFF 

--INSERT INTO APPLICATION_DATA_FOR_EMPLOYEE

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE ON
INSERT INTO dbo.DATA_APPLICATION_FOR_EMPLOYEE (ID,MaNV,TenNV,UserName,UserPassword,TAI_KHOANG,NGAY_DANG_NHAP)
SELECT APPLICATION_USER.ID,'NV02','TRAN VO LOC', APPLICATION_USER.UserName, APPLICATION_USER.UserPassword,APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM APPLICATION_USER 
WHERE APPLICATION_USER.ID=4;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE OFF 

SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE ON
INSERT INTO dbo.DATA_APPLICATION_FOR_EMPLOYEE (ID,MaNV,TenNV,UserName,UserPassword,TAI_KHOANG,NGAY_DANG_NHAP)
SELECT APPLICATION_USER.ID,'NV03','LE PHU KHAI', APPLICATION_USER.UserName, APPLICATION_USER.UserPassword,APPLICATION_USER.TAI_KHOANG,'12/21/2022'
FROM APPLICATION_USER 
WHERE APPLICATION_USER.ID=5;
SET IDENTITY_INSERT dbo.DATA_APPLICATION_FOR_EMPLOYEE OFF 

ALTER TABLE dbo.DATA_APPLICATION_FOR_ADMIN ADD CONSTRAINT FK_DATA_APPLICATION_FOR_ADMIN FOREIGN KEY (ID,UserName,UserPassword) REFERENCES dbo.APPLICATION_USER(ID,UserName,UserPassword)
ALTER TABLE dbo.DATA_APPLICATION_FOR_MANAGER ADD CONSTRAINT FK_DATA_APPLICATION_FOR_MANAGER FOREIGN KEY (ID,UserName,UserPassword) REFERENCES dbo.APPLICATION_USER(ID,UserName,UserPassword)
ALTER TABLE dbo.DATA_APPLICATION_FOR_EMPLOYEE ADD CONSTRAINT FK_DATA_APPLICATION_FOR_EMPLOYEE FOREIGN KEY (ID,UserName,UserPassword) REFERENCES dbo.APPLICATION_USER(ID,UserName,UserPassword)