SELECT COUNT (UserName) as 'RETURN_COUNTCOLUMN' from DATA_APPLICATION_REGISTER 
SELECT UserName FROM DATA_APPLICATION_REGISTER
SELECT * FROM DATA_APPLICATION_REGISTER

INSERT INTO DATA_APPLICATION_REGISTER VALUES('{UserName}',PWDENCRYPT('{UserPassword'),'{FristName}','{LastName}','{EmailAdress}','{Date_of_birth','{NGAY_DANG_KY}','{TAI_KHOANG}','{TINH_TRANG}')


INSERT INTO DATA_APPLICATION_REGISTER VALUES('Nv04',PWDENCRYPT('Nv04@123'),'TRAN','LONG','Nv04@gmail.com','04/12/1996','12/28/2022',null,'CHUA DUYET')

DELETE DATA_APPLICATION_REGISTER WHERE UserName='khanhyou2018'